#!/bin/bash
#
#  Copyright (C) 2014 Karl Lindén
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#  
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.
#  

# Remove empty directories

remove_empty_dirs() {
	local path=${1}
	local remove=true
	local contents=$(ls -A ${path})
	for c in ${contents}; do
		if [ "${c}" != .svn ]; then
			local fullc="${path}/${c}"
			if [ -d ${fullc} ]; then
				local removed=$(remove_empty_dirs ${fullc})
				[[ "${removed}" == true ]] || remove=false
			else
				remove=false
			fi
		fi
	done

	[[ "${remove}" = true ]] && svn del ${path}

	echo "${remove}"
}

remove_empty_dirs . > /dev/null
