#!/bin/bash
# Distributed under the terms of the GNU General Public License v2
info_wrapper(){
cat << EOT
# This is a wrapper-script which is provided along with the
# aeolus ebuild in the:
# "pro audio production applications portage overlay" at
# http://forums.gentoo.org/viewtopic-t-427211.html

# This script is NOT support by the author of aelous
# so If you don't like it do the following:
# mv /usr/bin/aeolus-bin /usr/bin/aeolus
# otherwise enjoy the automatically setup
# Press any key to continue or CTRL+C to abort
# --evermind--
EOT
}
# script which copy files from
# /usr/share/stops/ to ~/.aelous and also creates ~/.aeolusrc with the right
# paths and jack-support enabled
# you can find a aeolus guide here: http://www.geocities.jp/midi_organ_net/aeolus/


[ "x${@}" ==  "x-h" ] && exec aeolus-bin "${@}"
if [ -e "${HOME}/.aeolusrc" -a  -d "${HOME}/.aeolus/" ];then
		echo "~/.aeolusrc exist ... launching aeolus"
	exec aeolus-bin "${@}"

else
	ANSWER="n"
	info_wrapper
	read
	
	echo "create configuration file ${HOME}/.aeolusrc"
	echo "and copy aeolus-stops files to "${HOME}/.aeolus/""
	echo "[y,n]"
	
	read ANSWER
	[ "${ANSWER}" != "y" ] && exit 0

	if [ ! -e "${HOME}/.aeolusrc" ];then
		gzip -cd /usr/share/aeolus-*/.aeolusrc.gz > "${HOME}/.aeolusrc"
		sed -i -e "s@^\(\!\ Aeolus.stops.*\)@Aeolus.stops: ${HOME}/.aeolus/stops@" "${HOME}/.aeolusrc" || exit 1
		sed -i -e "s@^\(\!\ Aeolus.waves.*\)@Aeolus.waves: waves@" "${HOME}/.aeolusrc" || exit 1
		sed -i -e 's@!\ Aeolus.jack@Aeolus.jack@g' "${HOME}/.aeolusrc" || exit 1
	fi
	
	if [ ! -d "${HOME}/.aeolus/" ];then
		mkdir -p "${HOME}/.aeolus/" || exit 1
		cp -a /usr/share/stops/ "${HOME}/.aeolus/" || exit 1 
	fi
	exec aeolus-bin "${@}"
fi
